import json, struct, pathlib, sys
root = pathlib.Path(sys.argv[1])
out = pathlib.Path(__file__).parents[1]/'assets/pnr/players'
out.mkdir(parents=True, exist_ok=True)
for source in ['1037', '1074', '1185']:
    data=(root/f'mh_{source}.glb').read_bytes()
    size=struct.unpack_from('<I',data,12)[0]
    doc=json.loads(data[20:20+size]); binary=data[28+size:]
    # Keep only MakeHuman's CC0 body, eyes and bundled hair. Third-party
    # clothing/accessories and all source motion capture are removed.
    allowed={'Human.body','iris','Human.short03','Human.short04'}
    for mesh in doc['meshes']:
        mesh['primitives']=[p for p in mesh['primitives'] if doc['materials'][p['material']]['name'] in allowed]
    doc.pop('animations',None)
    mats=sorted({p['material'] for m in doc['meshes'] for p in m['primitives']})
    for m in doc['meshes']:
        for p in m['primitives']: p['material']=mats.index(p['material'])
    doc['materials']=[doc['materials'][i] for i in mats]
    textures=set()
    def collect(v):
        if isinstance(v,dict):
            for k,x in v.items():
                if k.endswith('Texture') and isinstance(x,dict): textures.add(x['index'])
                else: collect(x)
        elif isinstance(v,list):
            for x in v: collect(x)
    collect(doc['materials']); textures=sorted(textures)
    def remap(v):
        if isinstance(v,dict):
            for k,x in v.items():
                if k.endswith('Texture') and isinstance(x,dict): x['index']=textures.index(x['index'])
                else: remap(x)
        elif isinstance(v,list):
            for x in v: remap(x)
    remap(doc['materials'])
    doc['textures']=[doc['textures'][i] for i in textures]
    images=sorted({t['source'] for t in doc['textures']})
    for t in doc['textures']: t['source']=images.index(t['source'])
    doc['images']=[doc['images'][i] for i in images]
    accessors=set()
    for m in doc['meshes']:
        for p in m['primitives']:
            accessors.update(p['attributes'].values());accessors.add(p['indices'])
    for s in doc['skins']: accessors.add(s['inverseBindMatrices'])
    accessors=sorted(accessors)
    for m in doc['meshes']:
        for p in m['primitives']:
            p['attributes']={k:accessors.index(v) for k,v in p['attributes'].items()}
            p['indices']=accessors.index(p['indices'])
    for s in doc['skins']: s['inverseBindMatrices']=accessors.index(s['inverseBindMatrices'])
    doc['accessors']=[doc['accessors'][i] for i in accessors]
    views=sorted({a['bufferView'] for a in doc['accessors']}|{i['bufferView'] for i in doc['images']})
    for a in doc['accessors']: a['bufferView']=views.index(a['bufferView'])
    for i in doc['images']: i['bufferView']=views.index(i['bufferView'])
    buf=bytearray(); kept=[]
    for i in views:
        view=dict(doc['bufferViews'][i]);start=view.get('byteOffset',0)
        while len(buf)%4:buf.append(0)
        view['byteOffset']=len(buf);buf.extend(binary[start:start+view['byteLength']]);kept.append(view)
    while len(buf)%4:buf.append(0)
    doc['bufferViews']=kept;doc['buffers']=[{'byteLength':len(buf)}]
    doc['asset']['copyright']='MakeHuman / MPFB2 CC0; bodies generated by MMWilliams char-kit. Source animations and third-party outfits excluded.'
    js=json.dumps(doc,separators=(',',':')).encode();js+=b' '*((-len(js))%4)
    glb=struct.pack('<III',0x46546c67,2,28+len(js)+len(buf))+struct.pack('<II',len(js),0x4e4f534a)+js+struct.pack('<II',len(buf),0x004e4942)+buf
    (out/f'player-{source}.glb').write_bytes(glb)
    print(source,len(glb))

